<a href="https://colab.research.google.com/github/JAYANTHNITW/NLP/blob/main/NLP_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df=pd.DataFrame({'text':['people watch campusx',
                         'campusx watch campusx',
                         'people write comment',
                         'campusx write comment'],
                 'output':[1,1,0,0]})

In [ ]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

# Applying BAG of Words with N_Grams techinque

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv =CountVectorizer(ngram_range=(3,3))
# if ngram_range=(1,1)--> Nothing but unigrams> nothing but taking one unique word in the voculabray
# if ngram_range=(2,2)--> Nothing but bi_grams> nothing but taking two combined unique words in the voculabary
# if ngram_range=(3,3)--> Nothing but tri_grams> nothing but taking 3 combined words in the voculabray
# if ngram_range=(1,2)--> Nothing but both unigrams and  bi_grams> taking both single and double unique combined words in the voculabray

In [ ]:
bow=cv.fit_transform(df['text'])

In [ ]:
# vocabulary
print(cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0]]
[[1 0 0 0]]


In [ ]:
cv.transform(['campusx watch and write in the comment section']).toarray()

array([[1, 1, 0, 1, 1]])

# Applying TF-IDF

In [ ]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [ ]:
print(tfidf.get_feature_names_out())
print(tfidf.idf_)

['campusx' 'comment' 'people' 'watch' 'write']
[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
